# Generated by Django 5.2.1 on 2026-07-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
