# Generated by Django 5.2.1 on 2026-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total contract value (INR). Milestones and invoices cannot exceed this.', max_digits=14),
        ),
    ]
