# Generated by Django 5.2.1 on 2026-07-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-employee_code'], 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
    ]
