# Generated by Django 5.2.1 on 2026-06-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wfh_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
