# Generated by Django 5.2.1 on 2026-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_code'], 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Is 2FA enabled for this employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32 TOTP secret for Google/Microsoft Authenticator', max_length=64, null=True),
        ),
    ]
