# Generated by Django 5.2.1 on 2026-07-29 05:16

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_options_employee_totp_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
