# Generated by Django 5.2.1 on 2026-07-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='is_system_account',
            field=models.BooleanField(default=False, help_text='System-level admin account (e.g., CEO Admin)'),
        ),
    ]
