# Generated by Django 5.2.1 on 2026-07-29 05:36

from django.db import migrations

def update_ceo_admin_flag(apps, schema_editor):
    Employee = apps.get_model('accounts', 'Employee')
    # Use update() on matches so it safely applies even if none exist
    # Based on the seed data, the CEO admin has employee_code = 'HIT-CEO', or first_name = 'CEO', last_name = 'Admin'
    Employee.objects.filter(employee_code='HIT-CEO').update(is_system_account=True)
    Employee.objects.filter(first_name='CEO', last_name='Admin').update(is_system_account=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_managers_employee_is_system_account'),
    ]

    operations = [
        migrations.RunPython(update_ceo_admin_flag, reverse_code=migrations.RunPython.noop),
    ]
