# Generated by Django 5.2.1 on 2026-08-06 05:08

import django.db.models.deletion
import packages.storages.dynamic_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PREFERENCE_PENDING', 'Preference Pending'), ('CLEARANCE_PENDING', 'Clearance Pending'), ('INTERVIEW_PENDING', 'Exit Interview Pending'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_records', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_initiated', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_offboarding_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_last_working_day', models.DateField(blank=True, null=True)),
                ('reason_for_leaving', models.TextField(blank=True, default='')),
                ('will_serve_notice_period', models.BooleanField(default=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='offboarding.offboardingrecord')),
            ],
            options={
                'db_table': 'hrms_offboarding_preference',
            },
        ),
        migrations.CreateModel(
            name='OffboardingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('RESIGNATION_LETTER', 'Resignation Letter'), ('RELIEVING_LETTER', 'Relieving Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('FNF_STATEMENT', 'Full & Final Settlement'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(storage=packages.storages.dynamic_storage.DynamicS3Storage, upload_to='offboarding-documents/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='offboarding.offboardingrecord')),
            ],
            options={
                'db_table': 'hrms_offboarding_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='offboarding.offboardingrecord')),
            ],
            options={
                'db_table': 'hrms_offboarding_exit_interview',
            },
        ),
        migrations.CreateModel(
            name='ClearanceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_items_cleared', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_items', to='offboarding.offboardingrecord')),
            ],
            options={
                'db_table': 'hrms_offboarding_clearance_item',
                'ordering': ['department', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingWorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_stages_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('offboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='offboarding.offboardingrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_offboarding_workflow_stage',
                'ordering': ['offboarding', 'order'],
            },
        ),
    ]
