# Generated by Django 5.2.1 on 2026-06-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmt_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transition',
            options={'ordering': ['source_state__order', 'destination_state__order'], 'verbose_name': 'transition', 'verbose_name_plural': 'transitions'},
        ),
    ]
