# Generated by Django 5.2.1 on 2026-06-29 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('timesheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, default='', help_text='Work performed')),
                ('remarks', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('BILLABLE', 'Billable'), ('NON_BILLABLE', 'Non-Billable'), ('INTERNAL', 'Internal'), ('TRAINING', 'Training'), ('SUPPORT', 'Support')], default='BILLABLE', max_length=15)),
                ('is_billable', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='tickets.ticket')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('weekly_timesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='timesheets.weeklytimesheet')),
            ],
            options={
                'db_table': 'project_work_log',
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['log_date', 'employee'], name='project_wor_log_dat_582d1a_idx'), models.Index(fields=['ticket', 'employee'], name='project_wor_ticket__293048_idx')],
            },
        ),
    ]
