# Generated by Django 5.2.1 on 2026-06-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0002_drop_workitem_add_ticket_fk'),
    ]

    operations = [
        # work_log_work_it_c29d0f_idx was already dropped when the work_item
        # field was removed in migration 0002 — no RemoveIndex needed here.

        # Rename the original (log_date, employee) index to the canonical name.
        migrations.RenameIndex(
            model_name='worklog',
            old_name='work_log_log_dat_5bbc2b_idx',
            new_name='project_wor_log_dat_582d1a_idx',
        ),
        # worklog_log_date_emp_idx is a duplicate on the same columns, added in
        # migration 0002 — drop it instead of renaming to the same target.
        migrations.RemoveIndex(
            model_name='worklog',
            name='worklog_log_date_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='worklog',
            old_name='worklog_ticket_emp_idx',
            new_name='project_wor_ticket__293048_idx',
        ),
    ]
