# Generated by Django 5.2.1 on 2026-07-09 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assignee',
        ),
        migrations.AddField(
            model_name='todo',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
