# Generated by Django 5.2.1 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_assignee_todo_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
