# Generated by Django 5.2.1 on 2026-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_content_todo_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
