# Generated by Django 5.2.1 on 2026-08-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='comments',
        ),
    ]
