# Generated by Django 5.2.1 on 2026-07-25 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='business_category',
            field=models.CharField(blank=True, choices=[('TRAINING', 'Training'), ('CONSULTING', 'Consulting'), ('SALES', 'Sales')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='deal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deal_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deal_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deal_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='deal_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
