# Generated by Django 5.2.1 on 2026-08-01 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_client_assigned_employees_clientchatroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_leads_m2m', to=settings.AUTH_USER_MODEL),
        ),
    ]
