# Generated by Django 5.2.1 on 2026-07-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='due_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='followup',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
