# Generated by Django 5.2.1 on 2026-07-12 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_followup_meeting_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='assignee',
        ),
        migrations.AddField(
            model_name='followup',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_followups', to=settings.AUTH_USER_MODEL),
        ),
    ]
