# Generated by Django 5.2.1 on 2026-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0004_remove_followup_assignee_followup_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20),
        ),
    ]
