# Generated by Django 5.2.1 on 2026-07-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0005_alter_followup_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
