# Generated by Django 5.2.1 on 2026-07-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0006_followup_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('SITE_VISIT', 'Site Visit')], default='CALL', max_length=20),
        ),
    ]
