# Generated by Django 5.2.1 on 2026-07-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0006_followup_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='type',
            field=models.CharField(default='CALL', max_length=100),
        ),
    ]
