# Generated by Django 5.2.1 on 2026-06-05 18:11

import django.db.models.deletion
import packages.storages.dynamic_storage
import packages.workflow.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmt_workflow', '0002_alter_transition_options'),
        ('tickets', '0004_add_attachment_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='original_estimate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated hours for this ticket', max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workflow_state',
            field=packages.workflow.field.StateField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='pmt_workflow.state'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(storage=packages.storages.dynamic_storage.DynamicS3Storage, upload_to='tickets/attachments/'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
