from django.urls import path
from .views import (
    EmployeeMonthlySummaryView, TodayAttendanceView, CheckInView, CheckOutView,
    MonthlyAttendanceView, StartBreakView, EndBreakView, AttendanceTrackerView,
    AttendanceExportView, AttendanceOverviewView, EmployeeCalendarView,
    LeaveTypeListView, MyLeaveBalancesView, MyLeaveRequestListView,
    LeaveRequestDetailView, LeaveReviewView, LeaveAcknowledgeView, AdminLeaveRequestListView, LeaveAssignView,
    AttendanceListView, AttendanceClockInEnableView, EmployeeShiftView,
    EmployeeScheduleView, WFHSettingView,
    WFHRequestView, WFHRequestAdminView, WFHRequestReviewView,
    ShiftChangeRequestView, ShiftChangeRequestAdminView, ShiftChangeRequestReviewView,
    LeaveTeamMetaView, LeaveTeamRequestsView,
)

urlpatterns = [
    path("attendance/today/",                TodayAttendanceView.as_view(),              name="attendance-today"),
    path("attendance/check-in/",             CheckInView.as_view(),                      name="attendance-check-in"),
    path("attendance/check-out/",            CheckOutView.as_view(),                     name="attendance-check-out"),
    path("attendance/break/start/",          StartBreakView.as_view(),                   name="attendance-break-start"),
    path("attendance/break/end/",            EndBreakView.as_view(),                     name="attendance-break-end"),
    path("attendance/monthly/",              MonthlyAttendanceView.as_view(),            name="attendance-monthly"),
    path("attendance/overview/",             AttendanceOverviewView.as_view(),           name="attendance-overview"),
    path("attendance/tracker/",              AttendanceTrackerView.as_view(),            name="attendance-tracker"),
    path("attendance/export/",               AttendanceExportView.as_view(),             name="attendance-export"),
    path("attendance/list/",                 AttendanceListView.as_view(),               name="attendance-list"),
    path("attendance/enable-clockin/",       AttendanceClockInEnableView.as_view(),      name="attendance-enable-clockin"),
    path("attendance/employee-calendar/",    EmployeeCalendarView.as_view(),             name="attendance-employee-calendar"),
    path("attendance/employee-shifts/",      EmployeeShiftView.as_view(),                name="attendance-employee-shifts-list"),
    path("attendance/employee-shifts/<uuid:pk>/", EmployeeShiftView.as_view(),           name="attendance-employee-shifts-detail"),
    path("attendance/schedule/",             EmployeeScheduleView.as_view(),             name="attendance-schedule"),
    path("attendance/wfh-settings/",         WFHSettingView.as_view(),                   name="attendance-wfh-settings"),
    path("attendance/wfh-requests/",         WFHRequestView.as_view(),                   name="attendance-wfh-requests"),
    path("attendance/wfh-requests/admin/",   WFHRequestAdminView.as_view(),              name="attendance-wfh-requests-admin"),
    path("attendance/wfh-requests/<uuid:pk>/review/", WFHRequestReviewView.as_view(),    name="attendance-wfh-review"),
    path("attendance/shift-change-requests/",         ShiftChangeRequestView.as_view(),  name="attendance-shift-change"),
    path("attendance/shift-change-requests/admin/",   ShiftChangeRequestAdminView.as_view(), name="attendance-shift-change-admin"),
    path("attendance/shift-change-requests/<uuid:pk>/review/", ShiftChangeRequestReviewView.as_view(), name="attendance-shift-change-review"),
    path("leave/types/",                     LeaveTypeListView.as_view(),                name="leave-types"),
    path("leave/balances/",                  MyLeaveBalancesView.as_view(),              name="leave-balances"),
    path("leave/requests/",                  MyLeaveRequestListView.as_view(),           name="leave-requests"),
    path("leave/requests/<uuid:pk>/",        LeaveRequestDetailView.as_view(),           name="leave-request-detail"),
    path("leave/requests/<uuid:pk>/review/", LeaveReviewView.as_view(),                  name="leave-review"),
    path("leave/requests/<uuid:pk>/ack/",    LeaveAcknowledgeView.as_view(),             name="leave-ack"),
    path("leave/admin/requests/",            AdminLeaveRequestListView.as_view(),        name="leave-admin-requests"),
    path("leave/admin/assign/",              LeaveAssignView.as_view(),                  name="leave-admin-assign"),
    path("leave/team/meta/",                 LeaveTeamMetaView.as_view(),                name="leave-team-meta"),
    path("leave/team/requests/",             LeaveTeamRequestsView.as_view(),            name="leave-team-requests"),
    path("attendance/employee-summary/",     EmployeeMonthlySummaryView.as_view(),       name="employee-monthly-summary"),
]