# Generated by Django 5.2.1 on 2026-06-02 13:02

import django.db.models.deletion
import packages.storages.dynamic_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('employee_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('alternative_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('total_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('prior_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('shift_applicable', models.BooleanField(default=False)),
                ('custom_shift_start', models.TimeField(blank=True, null=True)),
                ('custom_shift_end', models.TimeField(blank=True, null=True)),
                ('keycloak_group', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_pmo', models.BooleanField(default=False, help_text='PMO role flag')),
                ('is_manager', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, storage=packages.storages.dynamic_storage.DynamicS3Storage, upload_to='employees/profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master.department')),
                ('designation_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master.designation')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master.employmenttype')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master.grade')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master.location')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('shift_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master.shiftcategory')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'hrms_employee',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(blank=True, default='', max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(blank=True, null=True, storage=packages.storages.dynamic_storage.DynamicS3Storage, upload_to='employees/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_employee_certificate',
                'ordering': ['-issue_date'],
            },
        ),
    ]
