# Generated by Django 5.2.1 on 2026-06-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='allocation',
            new_name='project_all_employe_788ff6_idx',
            old_name='allocation_employe_5ce875_idx',
        ),
    ]
