# Generated by Django 5.2.1 on 2026-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
