# Generated by Django 5.2.1 on 2026-06-11 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendanceclockinenable_created_by_and_more'),
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceclockinenable',
            name='job_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendanceclockinenable',
            name='shift_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clockin_enables', to='master.shiftcategory'),
        ),
        migrations.CreateModel(
            name='LeaveMonthLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lock_type', models.CharField(default='MONTH', max_length=20)),
                ('lock_reason', models.CharField(default='PAYROLL_PROCESSING', max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('lop_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('lop_finalized', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_locks', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_locks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hrms_leave_month_lock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carry_forward', models.BooleanField(default=False)),
                ('carry_forward_limit', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('applicable_to', models.CharField(default='ALL', max_length=20)),
                ('effective_from', models.PositiveIntegerField()),
                ('effective_to', models.PositiveIntegerField(blank=True, null=True)),
                ('loss_of_pay_after', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('auto_allocate', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_policy_rules', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='attendance.leavetype')),
            ],
            options={
                'db_table': 'hrms_leave_policy_rule',
                'ordering': ['leave_type__name'],
            },
        ),
    ]
