# Generated by Django 5.2.1 on 2026-06-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_policy_lock_clockin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leavemonthlock',
            table='attendance_leave_month_lock',
        ),
        migrations.AlterModelTable(
            name='leavepolicyrule',
            table='attendance_leave_policy_rule',
        ),
    ]
