# Generated by Django 5.2.1 on 2026-07-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendanceregularization'),
        ('attendance', '0005_update_monthly_report_pm_ceo_flow'),
    ]

    operations = [
    ]
