# Generated by Django 5.2.1 on 2026-06-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_employeeshift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceclockinenable',
            options={'ordering': ['-date_from']},
        ),
        migrations.AlterUniqueTogether(
            name='attendanceclockinenable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendanceclockinenable',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceclockinenable',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceclockinenable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
