# Generated by Django 5.2.1 on 2026-07-25 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancemonthlyreport_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancemonthlyreport',
            unique_together={('reporting_manager', 'year', 'month')},
        ),
    ]
