# Generated by Django 5.2.1 on 2026-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendancemonthlyreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='leave_proofs/'),
        ),
    ]
