# Generated by Django 5.2.1 on 2026-07-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='cheque_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payroll',
            name='receipt_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payroll',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
