# Generated by Django 5.2.1 on 2026-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weeklytimesheet',
            new_name='weekly_time_employe_659205_idx',
            old_name='weekly_time_employe_0a8f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklytimesheet',
            new_name='weekly_time_status_375d2f_idx',
            old_name='weekly_time_status_9c3b1d_idx',
        ),
        migrations.AlterField(
            model_name='weeklytimesheet',
            name='week_end',
            field=models.DateField(help_text='Saturday of the week'),
        ),
        migrations.AlterField(
            model_name='weeklytimesheet',
            name='week_start',
            field=models.DateField(help_text='Sunday of the week'),
        ),
    ]
