# Generated by Django 5.2.1 on 2026-06-29 07:26

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('ADVANCE', 'Advance Invoice'), ('MILESTONE', 'Milestone Invoice'), ('FINAL', 'Final Invoice'), ('PROFORMA', 'Proforma Invoice'), ('REGULAR', 'Regular Invoice')], default='REGULAR', max_length=20)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, help_text='Pre-tax amount', max_digits=15)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST/Tax percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='invoice_amount + tax_amount', max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='payment/invoices/')),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payment_invoice',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of contract value', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
            ],
            options={
                'db_table': 'payment_milestone',
                'ordering': ['sequence', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('ONLINE_GATEWAY', 'Online Gateway'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], default='BANK_TRANSFER', max_length=20)),
                ('bank_reference', models.CharField(blank=True, default='', help_text='Cheque number / UTR / UPI ref / transaction ID', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='payment/receipts/')),
            ],
            options={
                'db_table': 'payment_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'payment_allocation',
                'ordering': ['-created_at'],
            },
        ),
    ]
