import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_number", models.CharField(blank=True, max_length=50, unique=True)),
                ("contract_value", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("billing_model", models.CharField(
                    choices=[
                        ("MILESTONE", "Milestone Billing"),
                        ("ADVANCE_FINAL", "Advance + Final"),
                        ("DIRECT", "Direct Invoice"),
                        ("RETAINER", "Retainer"),
                        ("AMC", "AMC / Annual Maintenance"),
                        ("SUBSCRIPTION", "Subscription"),
                        ("TIMESHEET", "Timesheet Based"),
                    ],
                    default="DIRECT",
                    max_length=20,
                )),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("attachment", models.FileField(blank=True, null=True, upload_to="payment/contracts/")),
                ("client", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="contracts",
                    to="projects.client",
                )),
                ("project", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="contracts",
                    to="projects.project",
                )),
                ("created_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_contract_created",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("updated_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_contract_updated",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"db_table": "payment_contract", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CustomerPO",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("po_number", models.CharField(max_length=100, unique=True)),
                ("po_date", models.DateField()),
                ("po_value", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("attachment", models.FileField(blank=True, null=True, upload_to="payment/po/")),
                ("notes", models.TextField(blank=True, default="")),
                ("client", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="purchase_orders",
                    to="projects.client",
                )),
                ("project", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="purchase_orders",
                    to="projects.project",
                )),
                ("contract", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="purchase_orders",
                    to="payment.contract",
                )),
                ("created_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_customerpo_created",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("updated_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_customerpo_updated",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"db_table": "payment_customer_po", "ordering": ["-po_date"]},
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("milestone_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(
                    choices=[("PENDING", "Pending"), ("INVOICED", "Invoiced"), ("PAID", "Paid")],
                    default="PENDING",
                    max_length=20,
                )),
                ("project", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="billing_milestones",
                    to="projects.project",
                )),
                ("contract", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="milestones",
                    to="payment.contract",
                )),
                ("created_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_milestone_created",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("updated_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_milestone_updated",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"db_table": "payment_milestone", "ordering": ["sequence", "due_date"]},
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(blank=True, max_length=50, unique=True)),
                ("invoice_type", models.CharField(
                    choices=[
                        ("ADVANCE", "Advance Invoice"),
                        ("MILESTONE", "Milestone Invoice"),
                        ("FINAL", "Final Invoice"),
                        ("PROFORMA", "Proforma Invoice"),
                        ("REGULAR", "Regular Invoice"),
                    ],
                    default="REGULAR",
                    max_length=20,
                )),
                ("invoice_date", models.DateField()),
                ("invoice_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("tax_percentage", models.DecimalField(decimal_places=2, default="18.00", max_digits=5)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("attachment", models.FileField(blank=True, null=True, upload_to="payment/invoices/")),
                ("is_cancelled", models.BooleanField(default=False)),
                ("client", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="invoices",
                    to="projects.client",
                )),
                ("project", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="invoices",
                    to="projects.project",
                )),
                ("contract", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="invoices",
                    to="payment.contract",
                )),
                ("milestone", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="invoices",
                    to="payment.milestone",
                )),
                ("purchase_order", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="invoices",
                    to="payment.customerpo",
                )),
                ("created_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_invoice_created",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("updated_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_invoice_updated",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"db_table": "payment_invoice", "ordering": ["-invoice_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_reference", models.CharField(blank=True, max_length=50, unique=True)),
                ("payment_date", models.DateField()),
                ("payment_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_mode", models.CharField(
                    choices=[
                        ("BANK_TRANSFER", "Bank Transfer"),
                        ("UPI", "UPI"),
                        ("CHEQUE", "Cheque"),
                        ("CASH", "Cash"),
                        ("ONLINE_GATEWAY", "Online Gateway"),
                        ("NEFT", "NEFT"),
                        ("RTGS", "RTGS"),
                    ],
                    default="BANK_TRANSFER",
                    max_length=20,
                )),
                ("bank_reference", models.CharField(blank=True, default="", max_length=100)),
                ("remarks", models.TextField(blank=True, default="")),
                ("attachment", models.FileField(blank=True, null=True, upload_to="payment/receipts/")),
                ("client", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="payments",
                    to="projects.client",
                )),
                ("project", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payments",
                    to="projects.project",
                )),
                ("created_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_payment_created",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("updated_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_payment_updated",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"db_table": "payment_payment", "ordering": ["-payment_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allocated_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("notes", models.TextField(blank=True, default="")),
                ("payment", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="allocations",
                    to="payment.payment",
                )),
                ("invoice", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="allocations",
                    to="payment.invoice",
                )),
                ("created_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_allocation_created",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("updated_by", models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="payment_allocation_updated",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"db_table": "payment_allocation", "ordering": ["-created_at"]},
        ),
    ]
