# Generated by Django 5.2.1 on 2026-06-11 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('year', models.PositiveIntegerField()),
                ('holiday_type', models.CharField(choices=[('GOVERNMENT', 'Government Holiday'), ('COMPANY', 'Company Holiday')], default='GOVERNMENT', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_holiday',
                'ordering': ['date'],
                'unique_together': {('date', 'name')},
            },
        ),
    ]
