# Generated by Django 5.2.1 on 2026-07-22 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupTypeMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(blank=True, default='#6366F1', max_length=50)),
            ],
            options={
                'verbose_name': 'followup type',
                'verbose_name_plural': 'followup types',
                'db_table': 'master_followup_type',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
