# Generated by Django 5.2.1 on 2026-07-25 06:20

from django.db import migrations


def rename_consultant(apps, schema_editor):
    BusinessType = apps.get_model('master', 'BusinessType')
    BusinessType.objects.filter(name='Consultant').update(name='Consulting')


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_followuptypemaster'),
    ]

    operations = [
        migrations.RunPython(rename_consultant, migrations.RunPython.noop),
    ]
