# Generated by Django 5.2.1 on 2026-07-30 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_update_business_type_consulting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='max_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Max days allowed per year (0 = unlimited)', max_digits=5),
        ),
        migrations.CreateModel(
            name='ReimbursementConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Standard Reimbursement Workflow', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_approve_below', models.DecimalField(decimal_places=2, default=0, help_text='Auto approve claims under this amount (0 = disabled)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Employee responsible for approving claims and auto-generating company expenses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_approval_configs', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Employee responsible for reviewing/checking claims', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_review_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reimbursement config',
                'verbose_name_plural': 'reimbursement configs',
                'db_table': 'master_reimbursement_config',
            },
        ),
    ]
