# Generated by Django 5.2.1 on 2026-07-31 04:16
# Hand-edited to add data-cleanup RunPython before schema changes.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def consolidate_to_singleton(apps, schema_editor):
    """
    Data migration: before applying the singleton constraint, ensure the table
    contains at most ONE valid row (most recently updated with a valid approver).
    All other rows are deleted so the subsequent schema changes cannot fail.

    Handles three scenarios:
    1. Table is empty → nothing to do.
    2. Table has exactly one valid row → nothing to do.
    3. Table has multiple rows → keep the newest, delete the rest.
    """
    ReimbursementConfig = apps.get_model('master', 'ReimbursementConfig')

    # Delete rows without an approver (invalid orphan data from old inserts)
    ReimbursementConfig.objects.filter(approver__isnull=True).delete()

    # Among remaining rows, keep only the most recently updated
    valid_rows = ReimbursementConfig.objects.order_by('-updated_at')
    if valid_rows.count() > 1:
        # Keep the first (newest), delete the rest
        keeper_pk = valid_rows.first().pk
        ReimbursementConfig.objects.exclude(pk=keeper_pk).delete()


def noop_reverse(apps, schema_editor):
    """Reverse migration is a no-op; we cannot restore deleted rows."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_leavetype_max_days_reimbursementconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 0: Clean up stale/duplicate rows BEFORE schema changes
        migrations.RunPython(consolidate_to_singleton, noop_reverse),

        migrations.AlterModelOptions(
            name='reimbursementconfig',
            options={'verbose_name': 'reimbursement config', 'verbose_name_plural': 'reimbursement config'},
        ),
        migrations.RemoveField(
            model_name='reimbursementconfig',
            name='auto_approve_below',
        ),
        migrations.RemoveField(
            model_name='reimbursementconfig',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='reimbursementconfig',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reimbursementconfig',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='reimbursementconfig',
            name='configured_by',
            field=models.ForeignKey(blank=True, help_text='The admin who last updated this configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_configs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursementconfig',
            name='is_singleton',
            field=models.BooleanField(default=True, editable=False, help_text='Internal sentinel. Always True. Prevents duplicate config rows.'),
        ),
        migrations.AlterField(
            model_name='reimbursementconfig',
            name='approver',
            field=models.ForeignKey(
                help_text='The single employee responsible for approving all reimbursement claims.',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reimbursement_approval_config',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='reimbursementconfig',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_singleton', True)),
                fields=('is_singleton',),
                name='unique_reimbursement_singleton',
            ),
        ),
    ]
