# Generated by Django 5.2.1 on 2026-07-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=16),
        ),
    ]
