# Generated by Django 5.2.1 on 2026-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ticket.assigned', 'Ticket Assigned'), ('ticket.due_today', 'Ticket Due Today'), ('project.allocation', 'Project Allocation'), ('project.manager_assigned', 'Project Manager Assigned'), ('project.due_reminder', 'Project Due Reminder'), ('timesheet.submitted', 'Timesheet Submitted'), ('timesheet.approved', 'Timesheet Approved'), ('timesheet.rejected', 'Timesheet Rejected'), ('employee.onboarded', 'Employee Onboarded'), ('leave.requested', 'Leave Requested'), ('payroll.finalized', 'Payroll Finalized'), ('invoice.due_reminder', 'Invoice Due Reminder'), ('milestone.due_reminder', 'Milestone Due Reminder'), ('payment.overdue', 'Payment Overdue'), ('followup.due_today', 'Follow-up Due Today'), ('followup.overdue', 'Follow-up Overdue'), ('followup.assigned', 'Follow-up Assigned'), ('social_post.pending_approval', 'Social Post Pending Approval'), ('social_post.published', 'Social Post Published'), ('todo.assigned', 'To-Do Assigned'), ('todo.transitioned', 'To-Do Transitioned'), ('chat.message.new', 'New Chat Message')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('ticket.assigned', 'Ticket Assigned'), ('ticket.due_today', 'Ticket Due Today'), ('project.allocation', 'Project Allocation'), ('project.manager_assigned', 'Project Manager Assigned'), ('project.due_reminder', 'Project Due Reminder'), ('timesheet.submitted', 'Timesheet Submitted'), ('timesheet.approved', 'Timesheet Approved'), ('timesheet.rejected', 'Timesheet Rejected'), ('employee.onboarded', 'Employee Onboarded'), ('leave.requested', 'Leave Requested'), ('payroll.finalized', 'Payroll Finalized'), ('invoice.due_reminder', 'Invoice Due Reminder'), ('milestone.due_reminder', 'Milestone Due Reminder'), ('payment.overdue', 'Payment Overdue'), ('followup.due_today', 'Follow-up Due Today'), ('followup.overdue', 'Follow-up Overdue'), ('followup.assigned', 'Follow-up Assigned'), ('social_post.pending_approval', 'Social Post Pending Approval'), ('social_post.published', 'Social Post Published'), ('todo.assigned', 'To-Do Assigned'), ('todo.transitioned', 'To-Do Transitioned'), ('chat.message.new', 'New Chat Message')], max_length=64, unique=True),
        ),
    ]
