# Generated by Django 5.2.1 on 2026-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ticket.assigned', 'Ticket Assigned'), ('ticket.due_today', 'Ticket Due Today'), ('project.allocation', 'Project Allocation'), ('project.manager_assigned', 'Project Manager Assigned'), ('project.due_reminder', 'Project Due Reminder'), ('timesheet.submitted', 'Timesheet Submitted'), ('timesheet.approved', 'Timesheet Approved'), ('timesheet.rejected', 'Timesheet Rejected'), ('employee.onboarded', 'Employee Onboarded'), ('leave.requested', 'Leave Requested'), ('payroll.finalized', 'Payroll Finalized'), ('invoice.due_reminder', 'Invoice Due Reminder'), ('milestone.due_reminder', 'Milestone Due Reminder'), ('payment.overdue', 'Payment Overdue'), ('followup.due_today', 'Follow-up Due Today'), ('followup.overdue', 'Follow-up Overdue'), ('followup.assigned', 'Follow-up Assigned'), ('followup.commented', 'Follow-up Commented'), ('followup.updated', 'Follow-up Updated'), ('meeting.due_today', 'Meeting Due Today'), ('meeting.overdue', 'Meeting Overdue'), ('meeting.assigned', 'Meeting Assigned'), ('meeting.commented', 'Meeting Commented'), ('meeting.updated', 'Meeting Updated'), ('social_post.pending_approval', 'Social Post Pending Approval'), ('social_post.published', 'Social Post Published'), ('todo.assigned', 'To-Do Assigned'), ('todo.transitioned', 'To-Do Transitioned'), ('todo.commented', 'To-Do Commented'), ('todo.updated', 'To-Do Updated'), ('chat.message.new', 'New Chat Message'), ('reimbursement.submitted', 'Reimbursement Submitted'), ('reimbursement.approved', 'Reimbursement Approved'), ('reimbursement.rejected', 'Reimbursement Rejected'), ('reimbursement.info_requested', 'Reimbursement Info Requested'), ('reimbursement.paid', 'Reimbursement Paid')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('ticket', 'Ticket'), ('project', 'Project'), ('allocation', 'Allocation'), ('timesheet', 'Timesheet'), ('employee', 'Employee'), ('leave', 'Leave Request'), ('payroll', 'Payroll'), ('invoice', 'Invoice'), ('milestone', 'Milestone'), ('payment', 'Payment'), ('followup', 'Follow-up'), ('meeting', 'Meeting'), ('social_post', 'Social Post'), ('todo', 'To-Do'), ('chat_message', 'Chat Message'), ('reimbursement', 'Reimbursement Claim')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('ticket.assigned', 'Ticket Assigned'), ('ticket.due_today', 'Ticket Due Today'), ('project.allocation', 'Project Allocation'), ('project.manager_assigned', 'Project Manager Assigned'), ('project.due_reminder', 'Project Due Reminder'), ('timesheet.submitted', 'Timesheet Submitted'), ('timesheet.approved', 'Timesheet Approved'), ('timesheet.rejected', 'Timesheet Rejected'), ('employee.onboarded', 'Employee Onboarded'), ('leave.requested', 'Leave Requested'), ('payroll.finalized', 'Payroll Finalized'), ('invoice.due_reminder', 'Invoice Due Reminder'), ('milestone.due_reminder', 'Milestone Due Reminder'), ('payment.overdue', 'Payment Overdue'), ('followup.due_today', 'Follow-up Due Today'), ('followup.overdue', 'Follow-up Overdue'), ('followup.assigned', 'Follow-up Assigned'), ('followup.commented', 'Follow-up Commented'), ('followup.updated', 'Follow-up Updated'), ('meeting.due_today', 'Meeting Due Today'), ('meeting.overdue', 'Meeting Overdue'), ('meeting.assigned', 'Meeting Assigned'), ('meeting.commented', 'Meeting Commented'), ('meeting.updated', 'Meeting Updated'), ('social_post.pending_approval', 'Social Post Pending Approval'), ('social_post.published', 'Social Post Published'), ('todo.assigned', 'To-Do Assigned'), ('todo.transitioned', 'To-Do Transitioned'), ('todo.commented', 'To-Do Commented'), ('todo.updated', 'To-Do Updated'), ('chat.message.new', 'New Chat Message'), ('reimbursement.submitted', 'Reimbursement Submitted'), ('reimbursement.approved', 'Reimbursement Approved'), ('reimbursement.rejected', 'Reimbursement Rejected'), ('reimbursement.info_requested', 'Reimbursement Info Requested'), ('reimbursement.paid', 'Reimbursement Paid')], max_length=64, unique=True),
        ),
    ]
