# Generated by Django 5.2.1 on 2026-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='last_read_message',
        ),
        migrations.RemoveField(
            model_name='messagemention',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagestar',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagedeliverystatus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='messagedeliverystatus',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='messagemention',
            name='mentioned_employee',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='messagestar',
            name='employee',
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='last_read_message_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
        migrations.DeleteModel(
            name='MessageDeliveryStatus',
        ),
        migrations.DeleteModel(
            name='MessageMention',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
        migrations.DeleteModel(
            name='MessageStar',
        ),
    ]
